# Generated by Django 5.2.5 on 2025-08-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_description_alter_product_image'),
    ]

    operations = [
    ]
