# Generated by Django 5.2.5 on 2025-08-31 14:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_favorites_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Потребує уточнення', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta_branch', 'Самовивіз з Нової Пошти'), ('nova_poshta_postomat', 'Самовивіз з поштоматів Нової Пошти'), ('meest_branch', 'Самовивіз з Meest ПОШТА'), ('ukrposhta_branch', 'Самовивіз з УКРПОШТИ'), ('meest_courier', 'Курʼєр Meest ПОШТА'), ('nova_poshta_courier', 'Курʼєр Нової Пошти')], default='nova_poshta_branch', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата картою Visa/MasterCard'), ('cash_on_delivery', 'Оплата під час отримання товару')], default='cash_on_delivery', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефону має бути у форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
